FROM nginx

WORKDIR  /var/www/html

# Copy src from context app
COPY --from=app . .

# COPY config files from context config
COPY --from=config nginx.conf /etc/nginx/nginx.conf

# Expose the port
EXPOSE 80

# Start the server
CMD ["nginx", "-g", "daemon off;"]